### PR TITLE
Add identifiers.org link to match results page

### PR DESCRIPTION
**Pull request by cthoyt**
This will allow users to quickly get more context

### CODE REVIEW

**Comment by bgyori** [comment]
Thanks! I've been thinking about this too but never implemented it. We will need to do a little bit more work to make all the links work (e.g., CHEBI:CHEBI:* doesn't resolve due to the double prefix). Perhaps constructing the link in Python and then sending it as a parameter for rendering could work. Let me know what you think and if I should make the changes or you want to.

**Comment by cthoyt** [comment]
Good point... constructing identifiers.org links isn't so straightfowards. @dhimmel and I have both done this a few different ways at this point

**Comment by bgyori** [comment]
Okay, I'm implementing something that will work for all the name spaces that can currently appear (and most others too).

**Comment by bgyori** [comment]
This works for everything currently in Gilda by default and should work for most other name spaces in general...

**Comment by dhimmel** [comment]
Leaving some links to Manubot's infrastructure for CURIEs / identifiers.org, in case this is helpful:

- [implementation](https://github.com/manubot/manubot/blob/b117c3a2b66a1fd6f061a30f585d3969bb064437/manubot/cite/curie/__init__.py)
- [test cases](https://github.com/manubot/manubot/blob/b117c3a2b66a1fd6f061a30f585d3969bb064437/manubot/cite/tests/test_curie.py#L49-L71)

**Comment by bgyori** [comment]
Thanks @dhimmel!

**Pull request merged**
