### PR TITLE
Fix double whitespace and typo in docstring

### PR DESCRIPTION
**Pull request by EFord36**
Hi,

I noticed a double whitespace while reading a docstring - thought I would pop it in a pull request while I was looking at it.

Thanks for Gilda!

### CODE REVIEW

**Comment by cthoyt** [comment]
Thank you, @EFord36!

**Comment by EFord36** [comment]
just noticed a typo in the same docstring as well - sorry, commited that as well before I'd seen you'd already looked at this: you're too quick for me!

Sorry for not noticing both before opening the PR in the first place.

**Comment by cthoyt** [comment]
@EFord36 it's possible to make additional edits in your PR

Screenshot 2022-11-16 at 11 04 36


click the name of the branch, then you can navigate inside your branch and edit files from the github interface

**Comment by EFord36** [comment]
Also it looks like a workflow run blocks merging, which I can't trigger myself, it has to be a maintainer.

**Review by bgyori — APPROVED** [review]
Thank you @EFord36!

**Pull request merged**
